import {
  SvgLogo,
  SvgCheck,
  SvgPointerLeft,
  SvgPointerRight,
  SvgEnter,
  SvgAddNote,
  SvgEnterActive,
  SvgCross,
  SvgReset,
  SvgCopy,
  SvgAvatarEmpty,
  SvgCleanTextInput,
  SvgNewMind,
  SvgShareMind,
  SvgShareConversation,
  SvgShareApp,
  SvgMenu,
  SvgDiscord,
  SvgTwitter,
  SvgShareMenu,
  SvgRate,
  SvgFeedback,
  SvgAbout,
  SvgTermsAndConditions,
  SvgPrivacyPolicy,
  SvgShareChatScreen
} from 'components/ui/Svg/General'

export const SVG_MAP = {
  Logo: SvgLogo,
  Check: SvgCheck,
  AddNote: SvgAddNote,
  PointerLeft: SvgPointerLeft,
  PointerRight: SvgPointerRight,
  Enter: SvgEnter,
  EnterActive: SvgEnterActive,
  Cross: SvgCross,
  Reset: SvgReset,
  Copy: SvgCopy,
  AvatarEmpty: SvgAvatarEmpty,
  CleanTextInput: SvgCleanTextInput,
  newMind: SvgNewMind,
  Share: SvgShareMenu,
  ShareMind: SvgShareMind,
  ShareConversation: SvgShareConversation,
  ShareChatScreen: SvgShareChatScreen,
  ShareApp: SvgShareApp,
  Menu: SvgMenu,
  Discord: SvgDiscord,
  Twitter: SvgTwitter,
  Rate: SvgRate,
  Feedback: SvgFeedback,
  About: SvgAbout,
  TermsAndConditions: SvgTermsAndConditions,
  PrivacyPolicy: SvgPrivacyPolicy
}
