import Config from 'react-native-config'

export const globalConfig = {
  TINY_URL: Config.TINY_URL,
  TINY_URL_API: Config.TINY_URL_API,
  TINY_URL_API_KEY: Config.TINY_URL_API_KEY,
  SIDEMIND_URL: Config.SIDEMIND_URL,
  DYNAMIC_LINK_BASE_URL: Config.DYNAMIC_LINK_BASE_URL,
  OPEN_AI_KEY: Config.OPEN_AI_KEY,
  APPLE_APP_ID: Config.APPLE_APP_ID,
  DISCORD_URL: Config.DISCORD_URL,
  TWITTER_URL: Config.TWITTER_URL,
  APP_STORE_LINK: Config.APP_STORE_LINK,
  FEEDBACK_URL: Config.FEEDBACK_URL,
  ABOUT_URL: Config.ABOUT_URL,
  TERMS_CONDITIONS: Config.TERMS_CONDITIONS,
  PRIVACY: Config.PRIVACY
}
